# server.port=8082
server:
  port: 8082

spring:
  application:
    name: registration-service
  datasource:
    url: jdbc:h2:mem:registrations
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true # see SQL statements printed/formatted in our terminal
  h2:
    console:
      enabled: true
      path: /h2-console

# Actuator, enable endpoints:
management:
  endpoints:
    web:
      exposure:
        include: health, info

# Used to store the address for the workshop service locally
workshop:
  service:
    url: http://localhost:8081